spring:
  application:
    name: quantum-quill-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_platform?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Custom Configuration
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 900000          # 15 minutes
    refresh-token:
      expiration: 604800000     # 7 days

  ai:
    gemini:
      api-key: "ADD_YOUR_API_KEY"
      model: gemini-2.5-flash-lite
      base-url: https://generativelanguage.googleapis.com/v1/models

logging:
  level:
    org.springframework.security: DEBUG
    com.knowledgeplatform: DEBUG

server:
  port: 8085
  error:
    include-message: always
